services:
  app:
    build:
      context: .
      dockerfile: ./docker_images/app/Dockerfile
    container_name: "tdd-app"
    volumes:
      - ./src/bff:/app:cached
      - ./src/test:/test:cached
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    tty: true
